# Generated by Django 5.2 on 2025-04-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casemilestone_successstory_lawyerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='complexity',
            field=models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], default='moderate', max_length=20),
        ),
    ]
