# Generated by Django 4.2 on 2025-05-12 05:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0004_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='CaseNotification',
        ),
    ]
