# Generated by Django 5.2 on 2025-04-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
