# Generated by Django 5.2 on 2025-04-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lawyerprofile_is_available'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='is_anonymous',
            new_name='anonymous',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='accounts.donorprofile'),
        ),
    ]
