# Generated by Django 5.2 on 2025-05-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='checkout_request_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, help_text='Email for payment confirmation', max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='reference',
            field=models.CharField(blank=True, help_text='Paystack payment reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount received, if different.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='callback_response',
            field=models.JSONField(blank=True, help_text='Raw payment gateway callback response.', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('PAYSTACK', 'Paystack'), ('CRYPTO', 'Cryptocurrency'), ('OTHER', 'Other')], default='PAYSTACK', max_length=20),
        ),
    ]
